# Generated by Django 3.0.5 on 2020-04-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(default='@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('service_dates', models.CharField(max_length=100, null=True)),
                ('hours_worked', models.IntegerField(null=True)),
                ('description', models.TextField(default='provide description of services performed')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_value_of_service', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='inkind.Volunteer')),
            ],
        ),
    ]
