# Generated by Django 3.0.5 on 2020-04-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email_address',
            field=models.CharField(default='@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=100, null=True)),
                ('hours', models.IntegerField(null=True)),
                ('description', models.TextField(default='provide description of services performed')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='inkind.Volunteer')),
            ],
        ),
    ]
