# Generated by Django 3.0.5 on 2020-04-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0002_auto_20200408_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='rate',
            new_name='hourly_rate',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='hours',
            new_name='hours_worked',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='dates',
            new_name='service_dates',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='total',
            new_name='total_value_of_service',
        ),
    ]
