# Generated by Django 3.0.5 on 2020-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0004_auto_20200408_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
