# Generated by Django 3.0.5 on 2020-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0005_auto_20200408_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
