# Generated by Django 3.0.5 on 2020-04-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0006_auto_20200408_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
    ]
