# Generated by Django 3.0.5 on 2020-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0007_remove_volunteer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
