# Generated by Django 3.0.5 on 2020-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0008_auto_20200408_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
