# Generated by Django 3.0.5 on 2020-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkind', '0009_auto_20200408_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
